### ISSUE TITLE
4 - Collect system metrics during the execution of an action

### ISSUE THREAD

**Issue by syntonyze** [GerritForge/gerritforge-health-service#18]
Currently the reward function has a component based on the action type.

The current implementation is a static mapping between action and cost [1].

Collecting metrics about the resources impact while running an action is an attempt of having a more accurate way of calculating the cost of each action.

We can have each action in `action-executors` to expose metrics about the resource consumption so the environment can use it to calculate the cost associated to an action execution.

[1]: https://github.com/GerritForge/gerritforge-health-service/blob/master/components/gym-gerrit/gerrit_env.py#L59

**Comment by geminicaprograms** [comment]
+1

**Comment by DanieleSassoli** [comment]
+1

**Comment by dariusj** [comment]
+1

**Comment by avilaplana** [comment]
+1
