### ISSUE TITLE
1 - Normalize search for reuse

### ISSUE THREAD

**Issue by syntonyze** [GerritForge/gerritforge-health-service#19]

**Comment by syntonyze** [comment]
We need a function that returns a 0 to 1 value, depending on which threshold (to be defined) the time taken falls into.

Generally search for reuse should be quick, so thresholds could be x hundred of millis (quick), x seconds (medium), x minutes (slow).

Notice that having a normalized value might not be enough for the reward implementation, we also need to consider the delta, somehow.

**Comment by geminicaprograms** [comment]
It is being normalised in [_reward_search_for_reuse](https://review.gerrithub.io/c/GerritForge/gerritforge-health-service/+/1178368/1/components/gym-gerrit/gerrit_env.py#168) function - could be reconsidered later

**Comment by DanieleSassoli** [comment]
+1
