### ISSUE TITLE
Discretise metrics for Q-Function

### ISSUE THREAD

**Issue by syntonyze** [GerritForge/gerritforge-health-service#22]

**Comment by syntonyze** [comment]
To implement a Q-Function to learn the value of an action in a particular state, we need to diminish the number of possible states, which, at the moment, is infinite.

This is not good, because Q-learning requires a _finite_ number of states.
To achieve that we need to _dimish_ the number of possible states, by bucketizing and discretizing the metrics from which the model has to learn.

**Comment by geminicaprograms** [comment]
To normalize:
* `numberoflooserefs`/ `numberoflooserefs`+`numberofpackedrefs`
* `proc_cpu_system_load` / `proc_cpu_num_cores`

Discretise it with rounding to a single decimal
