### ISSUE TITLE
7 - Implement an in-memory repository test scenario for running the Franco AI simulation

### ISSUE THREAD

**Issue by lucamilanesio** [GerritForge/gerritforge-health-service#49]
Try to use an memdisk and see how much JGit speeds up.
If we are not satisfied with the increment of speed (we expect 1000 or 10k times) use an in-memory repository

**Comment by dzsessona** [comment]
+2

**Comment by DanieleSassoli** [comment]
+1

**Comment by maczech** [comment]
+2

**Comment by dzsessona** [comment]
+1

**Comment by lucamilanesio** [comment]
+1

**Comment by barbasa** [comment]
+1

**Comment by dluksza** [comment]
+1

**Comment by lucamilanesio** [comment]
Waiting for @smcintosh  to come up with the final results of the in-memory disk.

**Comment by maczech** [comment]
First results:
https://docs.google.com/spreadsheets/d/1LNcxb7OMG65q-b7lEkzkD9yS36gf9bD7zHl0j5HEhjA/edit?usp=sharing

**Comment by lucamilanesio** [comment]
The _turbo switch_ for JGit to allow 10x faster pushes is based on this experimental change:
https://eclipse.gerrithub.io/c/eclipse-jgit/jgit/+/1194153

**Comment by lucamilanesio** [comment]
First optimisation that skips the connectivity checker after a `git-receive-pack`:
https://review.gerrithub.io/c/eclipse-jgit/jgit/+/1194276/2

It requires the Java system property `ghs.jgit.receive-pack.skip-connectivity-check=false`

**Comment by lucamilanesio** [comment]
Second optimisation that skips the Gerrit's receive commit validation and avoids expensive search for objects in the packlist:
https://gerrit-review.googlesource.com/c/gerrit/+/424506/1

It requires the Java system property `ghs.gerrit.receive-commits.skip-validation`

**Comment by lucamilanesio** [comment]
The custom Gerrit build for using the JGit speedups is based on this change:
https://gerrit-review.googlesource.com/c/gerrit/+/424507/1

**Comment by lucamilanesio** [comment]
@smcintosh you can use the `gerrit.war` file from [here](https://drive.google.com/file/d/1GyGQIBej5Er43-uhnDdgHLGxbeuedKYG/view?usp=sharing) and add the following extra configs to your `gerrit.config` file:

```
[container]
        javaOptions = "-Dghs.jgit.receive-pack.skip-connectivity-check=true"
        javaOptions = "-Dghs.gerrit.receive-commits.skip-validation=true=true"
[core]
        packedGitLimit = 16g
        packedGitUseStrongRefs = true
        deltaBaseCacheLimit = 1g
        packedGitOpenFiles = 1048576
```

Make sure that the number of files is unlimited for the gerrit process:
```
 ulimit -n unlimited
```

Also, make sure that your in-memory filesystem is used for the git repository and you have the following settings on your JGit config in `$HOME/.config/jgit`

```
[filesystem "Homebrew|17.0.11|/dev/disk4"]
        timestampResolution = 10 nanoseconds
        minRacyThreshold = 10 nanoseconds
```

On the above, the `/dev/disk4` needs to be the ramdisk device and also the `Homebrew|17.0.11` would need to be your JVM signature.

**Comment by lucamilanesio** [comment]
For creating a RAMDisk volume on MacOS (e.g. 16GB):
```
diskutil erasevolume HFS+ "RAMDisk" `hdiutil attach -nomount ram://33554432`
```

**Comment by lucamilanesio** [comment]
@smcintosh one more hint: when you push new changes, the dynamic discover a the merge base is very expensive and can be skipped altogether with the `-obase=<sha1>`.

Example of a fast push:
```
git push -obase=47e2e6ee44ff3a3cef8b87974561ae25b7a4a50a origin HEAD:refs/for/master
```
vs. the slow push:
```
git push origin HEAD:refs/for/master
```

The `47e2e6ee44ff3a3cef8b87974561ae25b7a4a50a` in the above example is simply the SHA1 of `refs/heads/master`

**Comment by lucamilanesio** [comment]
I've added the `cached-refdb` libModule, but that's not enough when reaching tens of millions of objects and hundreds of thousands of objects: creating a new change slows down up to *2.8s*.

When executing the `PackedBatchRefUpdate` it looks for conflicting refs in `PackedBatchRefUpdate.java:226` that makes a *full scan* of all refs without using the cache:

```
		Set<String> initialRefs = refdb.getRefs(RefDatabase.ALL).keySet();
```

**Comment by lucamilanesio** [comment]
Pushed [Change 1194395](https://review.gerrithub.io/c/eclipse-jgit/jgit/+/1194395) on JGit which allows to define a new property `ghs.jgit.ref-update.skip-check-conflicting-names` for skipping the expensive check for existing ref names conflicts.

**Comment by lucamilanesio** [comment]
Pushed [Change 1194400](https://review.gerrithub.io/c/eclipse-jgit/jgit/+/1194400) for skipping the duplicates objects detection, which consumes the majority of the time for adding new objects.

**Comment by lucamilanesio** [comment]
Pushed [Change 424920](https://gerrit-review.googlesource.com/c/gerrit/+/424920) for allowing disabling all stream events and Json events formatting, which is very expensive.

Requires the following extra config in `gerrit.config`:

```ini
[event "stream-events"]
  disableAll = true
```

**Comment by lucamilanesio** [comment]
Pushed JGit [Change 1194407](https://review.gerrithub.io/c/eclipse-jgit/jgit/+/1194407) that allows skipping the lock of loose refs upon ref-updates when setting the Java System Property `ghs.jgit.ref-update.skip-locking-loose-refs=true`

**Comment by lucamilanesio** [comment]
Pushed JGit [Change 1194428](https://review.gerrithub.io/c/eclipse-jgit/jgit/+/1194428) for skipping the object ids collision check with the Java System Property `https://review.gerrithub.io/c/eclipse-jgit/jgit/+/1194428=true`

**Comment by lucamilanesio** [comment]
Adding @geminicaprograms for the performance improvements that could be provided by the cached-refdb.

**Comment by lucamilanesio** [comment]
Improved the object-id to pack lookup performance by 100k times when having a large number of packs, thanks to [Change 1194476](https://eclipse.gerrithub.io/c/eclipse-jgit/jgit/+/1194476).

@smcintosh the improved Gerrit war can be downloaded from [GCloud Drive Here](https://drive.google.com/file/d/1fU_nc2euFOa4IQhfFQNaKDDXZHoRyP2x/view?usp=sharing). I am able to push 600 changes per minute, sustained also with a large number of refs.

I'll leave it running for the next 8 hours, which would allow me to create a mono-repo with 300k changes.

**Comment by lucamilanesio** [comment]
Now that the ghs-gym environment is running at full speed, we have another new bottleneck (this time: expected), which is the speed of updating the packed-refs file. Let’s discuss tomorrow and get some ideas / tasks on that. From my last observation, when I reach the 400 refs, the bottleneck is the read/write of the packed-refs to disk: most of the threads are waiting on the in-memory reentrant lock.

The bottleneck isn’t the read/write to disk though, but the encoding of the packed-refs in memory. There isn’t any streaming write but the whole content is created in memory, encoded in UTF-8 and then written to disk in one go.

That’s done for transactionality, without any buffering and forcing a fsync on disk.

The typical call stack is:
```
threads-80-     java.base@17.0.11/sun.nio.cs.UTF_8$Encoder.encodeBufferLoop(UTF_8.java:555)
threads-80-     java.base@17.0.11/sun.nio.cs.UTF_8$Encoder.encodeLoop(UTF_8.java:566)
threads-80-     java.base@17.0.11/java.nio.charset.CharsetEncoder.encode(CharsetEncoder.java:585)
threads-80-     java.base@17.0.11/java.nio.charset.CharsetEncoder.encode(CharsetEncoder.java:806)
threads-80-     java.base@17.0.11/java.nio.charset.Charset.encode(Charset.java:850)
threads-80-     java.base@17.0.11/java.nio.charset.Charset.encode(Charset.java:870)
threads-80-     org.eclipse.jgit.lib.Constants.encode(Constants.java:684)
threads-80-     org.eclipse.jgit.lib.RefWriter.writePackedRefs(RefWriter.java:168)
threads-80-     org.eclipse.jgit.internal.storage.file.RefDirectory.commitPackedRefs(RefDirectory.java:1134)
threads-80-     org.eclipse.jgit.internal.storage.file.PackedBatchRefUpdate.execute(PackedBatchRefUpdate.java:183)
threads-80-     org.eclipse.jgit.lib.BatchRefUpdate.execute(BatchRefUpdate.java:589)
```

**Comment by lucamilanesio** [comment]
> Now that the ghs-gym environment is running at full speed, we have another new bottleneck (this time: expected), which is the speed of updating the packed-refs file. Let’s discuss tomorrow and get some ideas / tasks on that. From my last observation, when I reach the 400 refs, the bottleneck is the read/write of the packed-refs to disk: most of the threads are waiting on the in-memory reentrant lock.
> 
> The bottleneck isn’t the read/write to disk though, but the encoding of the packed-refs in memory. There isn’t any streaming write but the whole content is created in memory, encoded in UTF-8 and then written to disk in one go.
> 
> That’s done for transactionality, without any buffering and forcing a fsync on disk.
> 
> The typical call stack is:
> 
> ```
> threads-80-     java.base@17.0.11/sun.nio.cs.UTF_8$Encoder.encodeBufferLoop(UTF_8.java:555)
> threads-80-     java.base@17.0.11/sun.nio.cs.UTF_8$Encoder.encodeLoop(UTF_8.java:566)
> threads-80-     java.base@17.0.11/java.nio.charset.CharsetEncoder.encode(CharsetEncoder.java:585)
> threads-80-     java.base@17.0.11/java.nio.charset.CharsetEncoder.encode(CharsetEncoder.java:806)
> threads-80-     java.base@17.0.11/java.nio.charset.Charset.encode(Charset.java:850)
> threads-80-     java.base@17.0.11/java.nio.charset.Charset.encode(Charset.java:870)
> threads-80-     org.eclipse.jgit.lib.Constants.encode(Constants.java:684)
> threads-80-     org.eclipse.jgit.lib.RefWriter.writePackedRefs(RefWriter.java:168)
> threads-80-     org.eclipse.jgit.internal.storage.file.RefDirectory.commitPackedRefs(RefDirectory.java:1134)
> threads-80-     org.eclipse.jgit.internal.storage.file.PackedBatchRefUpdate.execute(PackedBatchRefUpdate.java:183)
> threads-80-     org.eclipse.jgit.lib.BatchRefUpdate.execute(BatchRefUpdate.java:589)
> ```
> 
> From the above, it is clear that having an in-memory filesystem won't help, because the bottleneck is the Charset encoding from String to UTF-8.

This is now fixed by https://eclipse.gerrithub.io/c/eclipse-jgit/jgit/+/1195180/1

**Comment by lucamilanesio** [comment]
The last missing piece of the jigsaw is the update of packed-refs, which still takes around 300ms for a 500k refs.

**Comment by lucamilanesio** [comment]
@maczech can experiment on batching the updates to `packed-refs` by:
- Number of writes per minute (e.g. max 50)
- Time between a write and the latest one (e.g. min 1s)
